#ifndef ICONS_H
#define ICONS_H

extern const char *fileopen_xpm[];

extern const char *filesaveas_xpm[];

extern const char *fileprint_xpm[];

extern const char *editcut_xpm[];

extern const char *editcopy_xpm[];

extern const char *editpaste_xpm[];

extern const char *editdelete_xpm[];

extern const char *smDolphin_xpm[];

extern const char *about_xpm[];

extern const char *help_xpm[];

extern const char *RtArrow_xpm[];

extern const char *OKCheck_xpm[];

extern const char *CancelX_xpm[];

extern const char *toggle_xpm[];

extern const char *Exit_xpm[];

extern const char *New_xpm[];

extern const char FreeMe_jpg[];

/* Generated by reswrap version 4.0.0 */

#endif

